### ISSUE TITLE
Download button no longer appears

### ISSUE THREAD

**Issue by LazyTrader** [jacopo-j/WebXDownloader#12] opened 2021-11-23 05:32 UTC
Used to be able to see the download button 1-2 days prior but when I open any webex recordings now, the download button no longer appears. The download button also does not appear when the recording is played and refreshing has no effect.
![image](https://user-images.githubusercontent.com/68470814/142975664-822d1e60-4497-4d5f-af0d-67d607b2ada0.png)

**Comment by LazyTrader** [comment] 2021-11-23 05:38
Also got this exception when running the extension.
![image](https://user-images.githubusercontent.com/68470814/142975990-b111b1a4-9336-40af-95c8-2d5c05fe32ff.png)

**Comment by LazyTrader** [comment] 2021-11-23 05:42
Error as shown:
![image](https://user-images.githubusercontent.com/68470814/142976269-dfbb8b0f-8077-43ae-81ec-59d4648cbe16.png)

**Comment by jacopo-j** [comment] 2021-11-24 13:53
This seems to be a duplicate of #11, see my comment there. The extension works fine with ”classic“ recordings.

**Closed by jacopo-j** 2021-11-24 13:53 UTC
